# generate_gateway_data.py
#
# Pulls 5-10 real Razorpay Test Mode order/payment records and merges them
# into data/gateway.json alongside your existing synthetic records.
# Per master_build_plan.md Part 4, Phase 1, Step 1.3.
#
# Prereqs:
#   1. RAZORPAY_KEY_ID / RAZORPAY_KEY_SECRET set in .env (Test Mode keys only)
#   2. data/invoices.json already generated by generate_synthetic_data.py
#
# Usage: python generate_gateway_data.py --count 8

import json
import argparse
from pathlib import Path
from src.razorpay_client import RazorpayTestClient

DATA_DIR = Path("data")


def load_invoices(n: int) -> list[dict]:
    with open(DATA_DIR / "invoices.json") as f:
        invoices = json.load(f)
    return invoices[:n]


def simulate_and_export(count: int) -> list[dict]:
    client = RazorpayTestClient()
    invoices = load_invoices(count)
    gateway_records = []

    for inv in invoices:
        order = client.create_test_order(
            amount_rupees=float(inv["amount"]),
            receipt=inv["invoice_id"],
            notes={"vendor": inv["vendor_name"]},
        )
        print(f"Created order {order['id']} for invoice {inv['invoice_id']}")
        print(
            "  -> In Test Mode, complete this payment via the Razorpay Checkout "
            "sandbox using the test UPI VPA 'success@razorpay', then re-run "
            "with --fetch-only to pull the resulting payment record."
        )

        payments = client.fetch_payments_for_order(order["id"])
        for payment in payments.get("items", []):
            gateway_records.append(client.to_gateway_record(order, payment))

    return gateway_records


def merge_into_existing_gateway_file(new_records: list[dict]) -> None:
    gateway_path = DATA_DIR / "gateway.json"
    existing = []
    if gateway_path.exists():
        with open(gateway_path) as f:
            existing = json.load(f)
    merged = existing + new_records
    with open(gateway_path, "w") as f:
        json.dump(merged, f, indent=2, default=str)
    print(f"Merged {len(new_records)} Razorpay-sourced records into {gateway_path} "
          f"(total now {len(merged)}).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=8, help="How many test orders to create")
    args = parser.parse_args()

    records = simulate_and_export(args.count)
    if records:
        merge_into_existing_gateway_file(records)
    else:
        print("No payments captured yet. Complete the sandbox checkout for the "
              "created orders, then re-run this script.")
